<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260908135218 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE books (title VARCHAR(255) NOT NULL, authors TEXT NOT NULL, language VARCHAR(10) NOT NULL, cover_url VARCHAR(500) DEFAULT NULL, external_id VARCHAR(255) NOT NULL, genres TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4A1B2A929F75D7B0 ON books (external_id)');
        $this->addSql('CREATE TABLE chapters (chapter_number INT NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reading_club_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C721437125809907 ON chapters (reading_club_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_club_chapter_number ON chapters (reading_club_id, chapter_number)');
        $this->addSql('CREATE TABLE club_memberships (declared_chapter INT NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, reading_club_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58A81FFDA76ED395 ON club_memberships (user_id)');
        $this->addSql('CREATE INDEX IDX_58A81FFD25809907 ON club_memberships (reading_club_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_club ON club_memberships (user_id, reading_club_id)');
        $this->addSql('CREATE TABLE discussions (text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reading_club_id INT NOT NULL, chapter_id INT DEFAULT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B716B6325809907 ON discussions (reading_club_id)');
        $this->addSql('CREATE INDEX IDX_8B716B63579F4768 ON discussions (chapter_id)');
        $this->addSql('CREATE INDEX IDX_8B716B63F675F31B ON discussions (author_id)');
        $this->addSql('CREATE TABLE reading_clubs (name VARCHAR(255) NOT NULL, description TEXT NOT NULL, visibility VARCHAR(20) NOT NULL, chapter_count INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, host_id INT NOT NULL, current_book_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C98CF2A61FB8D185 ON reading_clubs (host_id)');
        $this->addSql('CREATE INDEX IDX_C98CF2A6BCAF3604 ON reading_clubs (current_book_id)');
        $this->addSql('CREATE TABLE reports (reported_content_type VARCHAR(20) NOT NULL, reported_content_id INT NOT NULL, reason TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reporter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11FA745E1CFE6F5 ON reports (reporter_id)');
        $this->addSql('CREATE TABLE reviews (text TEXT NOT NULL, contains_spoiler BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6970EB0F4EAFAD8B ON reviews (user_book_id)');
        $this->addSql('CREATE TABLE user_books (status VARCHAR(20) NOT NULL, rating INT DEFAULT NULL, progress INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A8D9D1CAA76ED395 ON user_books (user_id)');
        $this->addSql('CREATE INDEX IDX_A8D9D1CA16A2B381 ON user_books (book_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_book ON user_books (user_id, book_id)');
        $this->addSql('ALTER TABLE chapters ADD CONSTRAINT FK_C721437125809907 FOREIGN KEY (reading_club_id) REFERENCES reading_clubs (id)');
        $this->addSql('ALTER TABLE club_memberships ADD CONSTRAINT FK_58A81FFDA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE club_memberships ADD CONSTRAINT FK_58A81FFD25809907 FOREIGN KEY (reading_club_id) REFERENCES reading_clubs (id)');
        $this->addSql('ALTER TABLE discussions ADD CONSTRAINT FK_8B716B6325809907 FOREIGN KEY (reading_club_id) REFERENCES reading_clubs (id)');
        $this->addSql('ALTER TABLE discussions ADD CONSTRAINT FK_8B716B63579F4768 FOREIGN KEY (chapter_id) REFERENCES chapters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE discussions ADD CONSTRAINT FK_8B716B63F675F31B FOREIGN KEY (author_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE reading_clubs ADD CONSTRAINT FK_C98CF2A61FB8D185 FOREIGN KEY (host_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE reading_clubs ADD CONSTRAINT FK_C98CF2A6BCAF3604 FOREIGN KEY (current_book_id) REFERENCES books (id)');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA745E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F4EAFAD8B FOREIGN KEY (user_book_id) REFERENCES user_books (id)');
        $this->addSql('ALTER TABLE user_books ADD CONSTRAINT FK_A8D9D1CAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE user_books ADD CONSTRAINT FK_A8D9D1CA16A2B381 FOREIGN KEY (book_id) REFERENCES books (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chapters DROP CONSTRAINT FK_C721437125809907');
        $this->addSql('ALTER TABLE club_memberships DROP CONSTRAINT FK_58A81FFDA76ED395');
        $this->addSql('ALTER TABLE club_memberships DROP CONSTRAINT FK_58A81FFD25809907');
        $this->addSql('ALTER TABLE discussions DROP CONSTRAINT FK_8B716B6325809907');
        $this->addSql('ALTER TABLE discussions DROP CONSTRAINT FK_8B716B63579F4768');
        $this->addSql('ALTER TABLE discussions DROP CONSTRAINT FK_8B716B63F675F31B');
        $this->addSql('ALTER TABLE reading_clubs DROP CONSTRAINT FK_C98CF2A61FB8D185');
        $this->addSql('ALTER TABLE reading_clubs DROP CONSTRAINT FK_C98CF2A6BCAF3604');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA745E1CFE6F5');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F4EAFAD8B');
        $this->addSql('ALTER TABLE user_books DROP CONSTRAINT FK_A8D9D1CAA76ED395');
        $this->addSql('ALTER TABLE user_books DROP CONSTRAINT FK_A8D9D1CA16A2B381');
        $this->addSql('DROP TABLE books');
        $this->addSql('DROP TABLE chapters');
        $this->addSql('DROP TABLE club_memberships');
        $this->addSql('DROP TABLE discussions');
        $this->addSql('DROP TABLE reading_clubs');
        $this->addSql('DROP TABLE reports');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE user_books');
    }
}
